download-external-modules: false
evaluate-variables: true
external-checks-git:
- https://github.com/gal-legit/attacker.git//checks
external-modules-download-path: .external_modules
run-all-external-checks: true
framework: all
output: cli