# !!! Important !!!
# any change to this workflow will not take into effect on the same PR and only after,
# because of security implications from target 'pull_request_target'

name: security

on:
  pull_request_target:
  push:
    branches:
      - main

permissions: read-all

jobs:
  checkov-secrets:
    runs-on: ubuntu-latest
    env:
      MY_SUPER_SECRET: 'PWNED'
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # this is needed to use the API key in a PR
      - name: Scan for secrets
        uses: bridgecrewio/checkov-action@master  # use latest and greatest
        with:
          config_file: .github/checkov.yaml
